port: "8080"
public folder: "html_files"
certificate file: "/etc/letsencrypt/live/calebalberto.duckdns.org/fullchain.pem"
private key file: "/etc/letsencrypt/live/calebalberto.duckdns.org/privkey.pem"
backend url: "http://localhost:3000"
